### ISSUE TITLE
Pre P.C. Ground Combat

### ISSUE THREAD

**Issue by pikiperry** [kylengelmann/pupProto#2]
Only check off when put into Unity.
#### Interactions
- [x] Get Hit
- [x] Get Knocked Back
- [x] Get Knocked Down?
- [x] On Death
#### Neutral Attacks
- [x] A
- [x] B
- [x] C
#### Forward Attacks
- [x] A
- [x] B
- [x] C
#### Upward Attacks (Each will launch and end current combo. C gives wind.)
- [x] A
~~- [ ] B~~
~~- [ ] C~~
#### Crouching Attack
- [x] A

**Comment by kylengelmann** [comment]
- [ ] does this add another?

**Comment by pikiperry** [comment]
art is complete, needs implementation into combat
